name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # Ensure this is set in your secrets if not hardcoding here

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/my-repository:${IMAGE_TAG} .
          docker push ${{ steps.login-ecr.outputs.registry }}/my-repository:${IMAGE_TAG}

      - name: Update kube config
        run: aws eks update-kubeconfig --name my-cluster-name  # Replace 'my-cluster-name' with your actual cluster name

      - name: Deploy nodejs helm chart to EKS
        run: |
          helm upgrade --install --force nodeapp ./node-app \
            --set image.repository=${{ steps.login-ecr.outputs.registry }}/my-repository \
            --set image.tag=${{ github.sha }}
