name: Build and push Docker image to ECR and deploy to EKS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: pranaydevopshelm
          IMAGE_TAG: ${{ github.sha }}
        run: |
          if [ -z "$REGISTRY" ]; then
            echo "ERROR: REGISTRY is not set."
            exit 1
          fi
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      - name: Update kube config
        run: aws eks update-kubeconfig --name demo  # Replace 'demo' with your cluster name
      - name: Deploy nodejs helm chart to EKS
        run: |
          helm upgrade --install --force nodeapp ./node-app \
            --set image.tag=${{ github.sha }}
